services:
  nginx-dev:
    container_name: ${APP_NAME}-nginx-dev
    image: nginx:1.27.3-alpine
    networks:
      - web_network
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/dev:/etc/nginx/conf.d/
    depends_on:
      - app-dev

  app-dev:
    container_name: ${APP_NAME}-app-dev
    build:
      context: ./
      dockerfile: ./docker/php/dev.Dockerfile
    volumes:
      - ./:/var/www
      - vendor_data:/var/www/vendor
    env_file:
      - .env
    networks:
      - db_network
      - web_network
    depends_on:
      - pgsql-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgsql-dev:
    container_name: ${APP_NAME}-pgsql-dev
    image: 'postgres:17-alpine'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'pgsql_data:/var/lib/postgresql/data'
    networks:
      - db_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d ${DB_DATABASE} -U ${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

networks:
  db_network:
  web_network:
volumes:
  pgsql_data:
  vendor_data:
