services:
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:1.27.3-alpine
    networks:
      - web_network
      - traefik_net
    volumes:
      - ./docker/nginx/prod:/etc/nginx/conf.d/
      - public_data:/var/www/public
      - icons_data:/var/www/public/icons:ro
      - images_data:/var/www/public/images:ro
      - uploads_data:/var/www/public/uploads:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"

      # HTTP Router (port 80) - redirect to HTTPS
      - "traefik.http.routers.humblebrains-web.rule=Host(`api.humblebrains.ru`) || Host(`www.api.humblebrains.ru`)"
      - "traefik.http.routers.humblebrains-web.entrypoints=web"
      - "traefik.http.routers.humblebrains-web.middlewares=redirect-to-https@file"

      # HTTPS Router (port 443) - serve TLS
      - "traefik.http.routers.humblebrains-secure.rule=Host(`api.humblebrains.ru`) || Host(`www.api.humblebrains.ru`)"
      - "traefik.http.routers.humblebrains-secure.entrypoints=websecure"
      - "traefik.http.routers.humblebrains-secure.tls.certresolver=myresolver"

  app:
    container_name: ${APP_NAME}-app
    build:
      context: ./
      dockerfile: ./docker/php/prod.Dockerfile
    image: ${DOCKER_USERNAME}/${APP_NAME}:app-${COMMIT_TAG}
    volumes:
      - public_data:/var/www/public
      - icons_data:/var/www/storage/data/icons
      - images_data:/var/www/storage/data/images
      - uploads_data:/var/www/storage/app/public
    env_file:
      - .env
    networks:
      - db_network
      - web_network
    depends_on:
      - pgsql

  pgsql:
    container_name: ${APP_NAME}-pgsql
    image: 'postgres:17-alpine'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'pgsql_data:/var/lib/postgresql/data'
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      retries: 3
      timeout: 5s

networks:
  web_network:
  db_network:
    internal: true
  traefik_net:
    external: true
volumes:
  pgsql_data:
  public_data:
  images_data:
  uploads_data:
  icons_data:
